### ISSUE TITLE
Is buffer-full event now working?

### ISSUE THREAD

**Issue by barzilaydn** [duff2013/UartEvent#1]
Hey,

I couldn't quite understand - from the examples and the README it seems that the RX buffer full event is working though on the other hand the REVISION file states that it currently does not work.

What is the current state of the RX Buffer-full event?

**Comment by duff2013** [comment]
I did whole refactor of the DMA RX code which changed how the DMA buffer is used "for the better" and making a buffer full event is not exactly trival now. Also I've been updating the Snooze library lately. So no the buffer full is not working even though there is an example. That being said, I'll get the buffer full event working this week.
